version: '3'
services:
  web:
    build: .
    context: .
    dockerfile: Dockerfile.dev
    ports:
      - :3000:3000"
    # Create volumes here so that the files in the Docker containers
    # can be synced up with the local changes
    volumes:
      - app/node_modules
      - .:/app
  tests:
    build:
      context:
      dockerfile: Dockerfile.dev
    volumes:
      - app/node_modules
      - .:/app
      command: ["npm", "run", "test"]

#docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app 7c489a25ed65