sudo : required
services:
  - docker

before_install:
  - docker build -t vannguyen48/docker-frontend -f Dockerfile.dev .

script:
  - docker run vannguyen48/docker-frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-frontend"
  env: "DockerFrontend-env"
  bucket-name: "elasticbeanstalk-us-east-1-487764425842"
  bucket-path: "docker-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"